export type Variant = { id: string; title: string; ml: number; price: number; currency: string; available: boolean };
export type Product = { id: string; title: string; description: string; variants: Variant[]; demo: boolean };
export type CartLine = { id: string; quantity: number; variant: Variant };
export type Cart = { id: string; lines: CartLine[]; total: number; checkoutUrl: string | null; demo: boolean };
export interface Commerce { getProduct(): Promise<Product>; getCart(id?: string): Promise<Cart>; add(id: string | undefined, variantId: string, quantity: number): Promise<Cart>; update(id: string, lineId: string, quantity: number): Promise<Cart>; }
// TODO(content): owner must approve prices, formula and product description before launch.
export const mockProduct: Product = { id: 'ceema', title: 'Ceema Coconut Hair Oil', description: 'A little time for you. A coconut hair oil ritual for your wash-day routine.', demo: true, variants: [{ id: 'demo-500', title: '500 ml', ml: 500, price: 349, currency: 'INR', available: true }, { id: 'demo-1000', title: '1 litre', ml: 1000, price: 599, currency: 'INR', available: true }] };
export function validQuantity(value: unknown, allowZero = false): number { if (typeof value !== 'number' || !Number.isInteger(value) || value < (allowZero ? 0 : 1) || value > 10) throw new Error('Choose a quantity between 1 and 10.'); return value; }
export const money = (amount: number, currency = 'INR') => new Intl.NumberFormat('en-IN', { style: 'currency', currency, maximumFractionDigits: amount % 1 ? 2 : 0 }).format(amount);
function pack(lines: CartLine[]): Cart { const data = lines.map(l => ({ v: l.variant.id, q: l.quantity })); return { id: Buffer.from(JSON.stringify(data)).toString('base64url'), lines, total: lines.reduce((sum, l) => sum + l.variant.price * l.quantity, 0), checkoutUrl: null, demo: true }; }
export const mockCommerce: Commerce = {
 async getProduct() { return mockProduct; },
 async getCart(id) { try { const data = JSON.parse(Buffer.from(id || 'W10', 'base64url').toString()); if (!Array.isArray(data) || data.length > 2) return pack([]); const lines: CartLine[] = data.map(({ v, q }: { v: string; q: number }) => { const variant = mockProduct.variants.find(x => x.id === v); if (!variant) throw Error(); return { id: v, variant, quantity: validQuantity(q) }; }); return pack(lines); } catch { return pack([]); } },
 async add(id, variantId, quantity) { validQuantity(quantity); const cart = await this.getCart(id); const variant = mockProduct.variants.find(v => v.id === variantId); if (!variant) throw new Error('Choose an available size.'); const line = cart.lines.find(l => l.variant.id === variantId); if (line) line.quantity = validQuantity(line.quantity + quantity); else cart.lines.push({ id: variantId, variant, quantity }); return pack(cart.lines); },
 async update(id, lineId, quantity) { validQuantity(quantity, true); const cart = await this.getCart(id); const line = cart.lines.find(l => l.id === lineId); if (!line) throw new Error('This item is no longer in your bag. Refresh and try again.'); line.quantity = quantity; return pack(cart.lines.filter(l => l.quantity > 0)); }
};
type ShopifyMoney = { amount: string; currencyCode: string };
type ShopifyVariant = { id: string; title: string; availableForSale: boolean; price: ShopifyMoney; selectedOptions: { name: string; value: string }[] };
const variantFields = 'id title availableForSale price { amount currencyCode } selectedOptions { name value }';
const cartFields = `id checkoutUrl cost { subtotalAmount { amount currencyCode } } lines(first: 50) { nodes { id quantity merchandise { ... on ProductVariant { ${variantFields} } } } }`;
function mapVariant(v: ShopifyVariant): Variant { const size = v.selectedOptions.map(o => o.value).join(' ').toLowerCase(); const ml = /1000|1\s*(l|litre|liter)\b/.test(size) ? 1000 : /500/.test(size) ? 500 : 0; if (!ml) throw new Error('The store size options must be 500 ml or 1 litre.'); return { id: v.id, title: ml === 1000 ? '1 litre' : '500 ml', ml, price: Number(v.price.amount), currency: v.price.currencyCode, available: v.availableForSale }; }
async function shopify<T>(query: string, variables: object = {}): Promise<T> { const domain = process.env.SHOPIFY_STORE_DOMAIN!; if (!/^[a-z0-9][a-z0-9-]*\.myshopify\.com$/i.test(domain)) throw new Error('Store configuration needs attention.'); const response = await fetch(`https://${domain}/api/${process.env.SHOPIFY_API_VERSION || '2026-07'}/graphql.json`, { method: 'POST', headers: { 'Content-Type': 'application/json', 'X-Shopify-Storefront-Access-Token': process.env.SHOPIFY_STOREFRONT_ACCESS_TOKEN! }, body: JSON.stringify({ query, variables }), cache: 'no-store', signal: AbortSignal.timeout(12000) }); if (!response.ok) throw new Error('The shop is temporarily unavailable. Please try again.'); const result = await response.json(); if (result.errors) throw new Error('The shop could not complete that request. Please try again.'); return result.data; }
type RawCart = { id: string; checkoutUrl: string; cost: { subtotalAmount: ShopifyMoney }; lines: { nodes: { id: string; quantity: number; merchandise: ShopifyVariant }[] } };
function mapCart(c: RawCart): Cart { return { id: c.id, checkoutUrl: c.checkoutUrl, demo: false, total: Number(c.cost.subtotalAmount.amount), lines: c.lines.nodes.map(l => ({ id: l.id, quantity: l.quantity, variant: mapVariant(l.merchandise) })) }; }
async function mutate(name: string, declaration: string, args: string, variables: object) { const data = await shopify<Record<string, { cart: RawCart; userErrors: { message: string }[] }>>(`mutation(${declaration}) { ${name}(${args}) { cart { ${cartFields} } userErrors { message } } }`, variables); const result = data[name]; if (result.userErrors.length) throw new Error(result.userErrors[0].message); return mapCart(result.cart); }
const liveCommerce: Commerce = {
 async getProduct() { const data = await shopify<{ product: { id: string; title: string; description: string; variants: { nodes: ShopifyVariant[] } } | null }>(`query($handle: String!) { product(handle: $handle) { id title description variants(first: 10) { nodes { ${variantFields} } } } }`, { handle: process.env.SHOPIFY_PRODUCT_HANDLE || 'ceema-coconut-hair-oil' }); if (!data.product) throw new Error('This product is not currently available.'); return { ...data.product, variants: data.product.variants.nodes.map(mapVariant), demo: false }; },
 async getCart(id) { if (!id) return { id: '', lines: [], total: 0, checkoutUrl: null, demo: false }; const data = await shopify<{ cart: RawCart | null }>(`query($id: ID!) { cart(id: $id) { ${cartFields} } }`, { id }); return data.cart ? mapCart(data.cart) : { id: '', lines: [], total: 0, checkoutUrl: null, demo: false }; },
 async add(id, variantId, quantity) { validQuantity(quantity); const existing = id ? await this.getCart(id) : null; if (!existing?.id) return mutate('cartCreate', '$input: CartInput!', 'input: $input', { input: { lines: [{ merchandiseId: variantId, quantity }] } }); return mutate('cartLinesAdd', '$cartId: ID!, $lines: [CartLineInput!]!', 'cartId: $cartId, lines: $lines', { cartId: id, lines: [{ merchandiseId: variantId, quantity }] }); },
 async update(id, lineId, quantity) { validQuantity(quantity, true); return quantity === 0 ? mutate('cartLinesRemove', '$cartId: ID!, $lineIds: [ID!]!', 'cartId: $cartId, lineIds: $lineIds', { cartId: id, lineIds: [lineId] }) : mutate('cartLinesUpdate', '$cartId: ID!, $lines: [CartLineUpdateInput!]!', 'cartId: $cartId, lines: $lines', { cartId: id, lines: [{ id: lineId, quantity }] }); }
};
export function commerce(): Commerce { const domain = process.env.SHOPIFY_STORE_DOMAIN; const token = process.env.SHOPIFY_STOREFRONT_ACCESS_TOKEN; if (Boolean(domain) !== Boolean(token)) throw new Error('Complete both Shopify environment variables to connect the store.'); return domain && token ? liveCommerce : mockCommerce; }
