'use client';
import Image from 'next/image';
import Link from 'next/link';
import { useState } from 'react';
import { assets } from '@/lib/assets';
import type { Product } from '@/lib/commerce';
import { money } from '@/lib/commerce';
import { Bottle } from './store';
import { Icon } from './icons';
import { Form } from './forms';
export function Feature() { return <section className="section feature"><div className="feature-stage"><Bottle/><span className="stage-caption">Your bathroom shelf’s new regular.</span></div><div className="feature-copy"><h2>Good hair starts<br/>with a little care.</h2><p>Not another complicated routine. Just a bottle of coconut hair oil and a moment that’s all yours.</p><div className="benefit"><Icon name="coconut" size={33}/><div><h3>A coconut kind of ritual</h3><p>A familiar ingredient at the heart of your hair-care moment.</p></div></div><div className="benefit"><Icon name="hair" size={33}/><div><h3>Your hair. Your pace.</h3><p>Make a pre-wash oiling routine part of the time you take for yourself.</p></div></div><div className="benefit"><Icon name="bottle" size={33}/><div><h3>Little bottle. Longer ritual.</h3><p>Choose 500 ml or 1 litre to fit your shelf and your routine.</p></div></div><Link href="/product/ceema-coconut-hair-oil" className="text-link">Meet your hair oil</Link></div></section>; }
// TODO(content): Verify full INCI, fragrance, source, processing and formula before launch.
export function Ingredients() { return <section className="ingredients section" id="ingredients"><div className="ingredient-copy"><Icon name="coconut" size={46}/><h2>It starts<br/>with a coconut.</h2><p>Familiar for a reason. Coconut oil has a place in so many Indian hair-care routines. Ceema makes space for that everyday ritual, in a bottle you’ll want to keep close.</p><p className="quiet-note">Coconut hair oil is the product concept. The full ingredient list, fragrance and source details are awaiting brand confirmation.</p><Link href="/about" className="text-link">Get to know Ceema</Link></div><div className="ingredient-image"><Image src={assets.ingredient} alt="Fresh coconut halves in clear water under tropical light" fill sizes="(max-width: 700px) 100vw, 50vw"/></div></section>; }
const concerns = { Dryness: { title: 'Give your wash day a little more care.', text: 'Build in a gentle pre-wash oiling moment, using a small amount on the lengths. How your hair feels will depend on your hair and the final formula.' }, Frizz: { title: 'Get to know your own texture.', text: 'Start with a small amount and see how it fits your routine. Frizz is a natural part of many hair textures; no perfectly smooth hair promises here.' }, 'Hair fall': { title: 'Care, without the big promises.', text: 'Ceema is a cosmetic hair oil, not a treatment for hair loss. Persistent or sudden shedding needs advice from a qualified dermatologist.' }, Dandruff: { title: 'Know what your scalp needs.', text: 'This hair oil is not a dandruff treatment. If your scalp is itchy, flaky or irritated, speak with a qualified dermatologist about suitable care.' } };
export function ConcernPicker() { const [selected, setSelected] = useState<keyof typeof concerns>('Dryness'); return <section className="section concerns"><div><h2>What’s on<br/>your hair’s mind?</h2><p>A little guidance for your next wash day.</p></div><div><div className="filters" aria-label="Choose your hair concern">{Object.keys(concerns).map(c => <button key={c} aria-pressed={selected === c} onClick={() => setSelected(c as keyof typeof concerns)}>{c}</button>)}</div><div className="concern-answer" role="status"><Icon name="hair" size={36}/><h3>{concerns[selected].title}</h3><p>{concerns[selected].text}</p></div></div></section>; }
// TODO(content): Brand approval required for directions and patch-test guidance.
export function HowTo() { return <section className="section how-to" id="how-to"><div className="section-heading"><h2>Less rush.<br/>More ritual.</h2><p>Make a little room before wash day.<br/>Follow the final product label when available.</p></div><ol className="steps">{[{ icon: 'drop', title: 'Start small', text: 'Pour a small amount into your palms. Begin with less; you can always adjust.' }, { icon: 'hair', title: 'Take your time', text: 'Work gently through your lengths. Avoid irritated skin and contact with eyes.' }, { icon: 'coconut', title: 'Wash & carry on', text: 'Wash out with your usual shampoo. Find the amount that suits your hair.' }].map((s, i) => <li key={s.title}><div className="step-top"><span>0{i + 1}</span><Icon name={s.icon} size={44}/></div><h3>{s.title}</h3><p>{s.text}</p></li>)}</ol><p className="quiet-note">Illustrative routine. Final directions and patch-test guidance must be approved by the brand.</p></section>; }
export function Comparison() { return <section className="section comparison"><div><h2>Clear choices.<br/>No tall claims.</h2><p>Here’s what you can compare today. For everything else, the label should do the talking.</p></div><div className="table-wrap"><table><caption>Ceema and other hair oils: check the details</caption><thead><tr><th scope="col">What to check</th><th scope="col">Ceema</th><th scope="col">Other hair oils</th></tr></thead><tbody><tr><th scope="row">Product format</th><td>Coconut hair oil</td><td>Check product label</td></tr><tr><th scope="row">Bottle sizes</th><td>500 ml & 1 litre</td><td>Varies by product</td></tr><tr><th scope="row">Price per ml</th><td>Shown for each size</td><td>Calculate from pack price</td></tr><tr><th scope="row">Formula & testing</th><td>Details pending verification</td><td>Check brand documentation</td></tr></tbody></table></div></section>; }
export function Quality() { return <section className="section quality"><div><h2>Proof belongs<br/>in the open.</h2><p>We’ll share the documents behind the bottle here, once they’re verified.</p></div><div className="proof-links"><a href="/documents/lab-report-placeholder.txt" download><Icon name="drop"/><span><strong>Lab report</strong><small>Placeholder document · not a test result</small></span><span aria-hidden="true">↓</span></a><a href="/documents/certification-placeholder.txt" download><Icon name="check"/><span><strong>Certifications</strong><small>Placeholder document · none claimed</small></span><span aria-hidden="true">↓</span></a></div></section>; }
export function SizePicker({ product }: { product: Product }) { return <section className="section sizes" id="sizes"><div className="section-heading"><div><h2>Pick your kind<br/>of everyday.</h2><p>Same coconut ritual. A size that feels like you.</p></div>{product.demo && <p className="preview-note">Illustrative prices, awaiting confirmation.</p>}</div><div className="size-options">{product.variants.map(v => <Link className="size-option" href={`/product/ceema-coconut-hair-oil?size=${v.ml}`} key={v.id}><div><span className="size-title">{v.title}</span><h3>{v.ml === 500 ? 'Your first hello.' : 'Stay a little longer.'}</h3><p>{v.ml === 500 ? 'A little space on your shelf.' : 'More room for your routine.'}</p><strong>{money(v.price, v.currency)}</strong><span className="per-ml">{money(v.price / v.ml, v.currency)} / ml</span><span className="button secondary">Choose {v.title}</span></div><Bottle size={String(v.ml)}/></Link>)}</div></section>; }
const faqs = [['What’s in Ceema Coconut Hair Oil?', 'Ceema is a coconut hair oil concept. The complete ingredient list, fragrance, processing method and concentration will be published once the brand has approved the final formula.'], ['Which size should I choose?', 'Choose 500 ml for a smaller bottle or 1 litre for a larger supply. Compare the price per ml next to each size. Preview prices are illustrative until the store is connected.'], ['Will it work for my hair type?', 'Hair routines are personal. Start with a small amount and follow the approved product label. We do not promise a particular result for any hair type.'], ['Does Ceema treat hair fall or dandruff?', 'No treatment claim is made. For persistent hair fall, dandruff or scalp irritation, ask a qualified dermatologist for guidance.'], ['Where do you deliver, and is COD available?', 'Delivery areas, shipping fees, estimated timing and cash-on-delivery availability will be confirmed at checkout once the store is live.'], ['Can I return my order?', 'The final return policy is awaiting brand approval. It will be available before orders can be placed. Contact us if you have a question.']];
export function FAQ() { return <section className="section faq"><div><h2>A few things<br/>you’re wondering.</h2><Link href="/contact" className="text-link">Ask us something else</Link></div><div className="accordion">{faqs.map(([q, a]) => <details key={q}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}</div></section>; }
// TODO(content): Confirm shipping, returns, COD and payment policy before launch.
export function TrustStrip() { return <div className="trust-strip">{[['shipping', 'Delivery', 'Availability at checkout'], ['return', 'Returns', 'Policy to be confirmed'], ['bag', 'Cash on delivery', 'Availability to be confirmed'], ['lock', 'Secure payment', 'Hosted Shopify checkout']].map(([icon, title, subtitle]) => <div key={title}><Icon name={icon} size={29}/><span><strong>{title}</strong><small>{subtitle}</small></span></div>)}</div>; }
export function Footer() { return <footer><div className="newsletter-wrap"><div><h2>A little good<br/>in your inbox.</h2><p>Hair rituals, Ceema news, and things worth sharing.</p></div><Form kind="newsletter"/></div><div className="footer-main"><Link className="wordmark footer-logo" href="/">ceema</Link><div><strong>Find your ritual</strong><Link href="/shop">Shop hair oil</Link><Link href="/#how-to">How to use</Link><Link href="/#hair-wall">The hair wall</Link></div><div><strong>A little about us</strong><Link href="/about">Our story</Link><Link href="/contact">Contact</Link><Link href="/policies">Shipping & returns</Link></div><div className="footer-note"><Icon name="coconut" size={38}/><p>Coconut care.<br/>For your kind of hair.</p></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Ceem Healthcare Private Limited.</span><Link href="/policies">Privacy & terms</Link><span>Made for a little me-time.</span></div></footer>; }


