'use client';
import Link from 'next/link';
import Image from 'next/image';
import { createContext, useContext, useEffect, useRef, useState } from 'react';
import type { Cart, Product, Variant } from '@/lib/commerce';
import { money } from '@/lib/commerce';
import { assets } from '@/lib/assets';
import { Icon } from './icons';
type Store = { cart: Cart | null; busy: boolean; error: string; open: boolean; setOpen: (v: boolean) => void; add: (variantId: string, quantity: number, buy?: boolean) => Promise<void>; update: (lineId: string, quantity: number) => Promise<void>; checkout: () => void };
const Context = createContext<Store | null>(null);
export function useStore() { const context = useContext(Context); if (!context) throw Error('Store unavailable'); return context; }
export function StoreProvider({ children }: { children: React.ReactNode }) { const [cart, setCart] = useState<Cart | null>(null); const [open, setOpen] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [toast, setToast] = useState(''); const lock = useRef(false);
 useEffect(() => { fetch('/api/cart').then(r => r.json()).then(data => data.error ? setError(data.error) : setCart(data)).catch(() => setError('Your bag could not load. Refresh to try again.')); }, []);
 useEffect(() => { if (!toast) return; const timer = setTimeout(() => setToast(''), 3500); return () => clearTimeout(timer); }, [toast]);
 const checkout = () => { if (cart?.checkoutUrl) window.location.assign(cart.checkoutUrl); else setError('This is a preview bag. Checkout will be available when the Shopify store is connected.'); };
 async function change(payload: object, buy = false) { if (lock.current) return; lock.current = true; setBusy(true); setError(''); try { const response = await fetch('/api/cart', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); const data = await response.json(); if (!response.ok) throw Error(data.error); setCart(data); if ('action' in payload && payload.action === 'add') { setToast('Added to cart'); setOpen(true); } if (buy) { if (data.checkoutUrl) window.location.assign(data.checkoutUrl); else setError('This is a preview bag. Connect Shopify to enable secure checkout.'); } } catch (e) { setError(e instanceof Error ? e.message : 'Could not update your bag. Try again.'); setOpen(true); } finally { lock.current = false; setBusy(false); } }
 return <Context.Provider value={{ cart, busy, error, open, setOpen, add: (variantId, quantity, buy) => change({ action: 'add', variantId, quantity }, buy), update: (lineId, quantity) => change({ action: 'update', lineId, quantity }), checkout }}>{children}<Modal open={open} onClose={() => setOpen(false)} title="Your bag" drawer><CartContents /></Modal><div className={`toast ${toast ? 'visible' : ''}`} role="status">{toast && <><Icon name="check" size={19}/>{toast}</>}</div></Context.Provider>;
}
export function Modal({ open, onClose, title, drawer, children }: { open: boolean; onClose: () => void; title: string; drawer?: boolean; children: React.ReactNode }) { const ref = useRef<HTMLDialogElement>(null); useEffect(() => { const dialog = ref.current; if (!dialog) return; if (open && !dialog.open) { dialog.showModal(); document.body.style.overflow = 'hidden'; } else if (!open) { dialog.close(); document.body.style.overflow = ''; } return () => { document.body.style.overflow = ''; }; }, [open]); return <dialog ref={ref} className={drawer ? 'drawer' : 'lightbox'} onCancel={onClose} onClick={e => { if (e.target === e.currentTarget) onClose(); }} aria-label={title}><div className="dialog-inner"><div className="dialog-heading"><h2>{title}</h2><button className="icon-button" onClick={onClose} aria-label="Close dialog"><Icon name="close"/></button></div>{children}</div></dialog>; }
export function Header() { const { cart, setOpen } = useStore(); const [menu, setMenu] = useState(false); const count = cart?.lines.reduce((n, l) => n + l.quantity, 0) || 0; return <><div className="announcement">A little coconut. A little time for you.</div><header className="header"><Link href="/" className="wordmark" aria-label="Ceema home">ceema<svg viewBox="0 0 20 25" aria-hidden="true"><path d="M10 1C7 7 1 11 1 16a9 9 0 0 0 18 0C19 11 13 7 10 1Z" fill="currentColor"/></svg></Link><nav className={menu ? 'nav is-open' : 'nav'} aria-label="Main navigation"><Link href="/shop" onClick={() => setMenu(false)}>Shop hair oil</Link><Link href="/about" onClick={() => setMenu(false)}>Our story</Link><Link href="/#hair-wall" onClick={() => setMenu(false)}>The hair wall</Link></nav><div className="header-actions"><Link href="/contact" className="contact-link">Let’s talk</Link><button className="bag-button" onClick={() => setOpen(true)} aria-label={`Open bag, ${count} items`}><Icon name="bag" size={21}/><span>Bag ({count})</span></button><button className="icon-button mobile-menu" aria-label="Toggle navigation" aria-expanded={menu} onClick={() => setMenu(!menu)}><Icon name={menu ? 'close' : 'menu'}/></button></div></header></>; }
export function Bottle({ size = '500', className = '' }: { size?: string; className?: string }) { return <div className={`bottle ${className}`}><Image src={size === '1000' ? assets.bottle1000 : assets.bottle500} alt={`Ceema Coconut Hair Oil ${size === '1000' ? '1 litre' : '500 ml'} concept bottle`} width={600} height={900} sizes="(max-width: 700px) 75vw, 35vw"/></div>; }
export function Quantity({ value, onChange, disabled }: { value: number; onChange: (n: number) => void; disabled?: boolean }) { return <div className="quantity" aria-label="Quantity"><button aria-label="Decrease quantity" disabled={disabled || value <= 1} onClick={() => onChange(value - 1)}>−</button><span aria-live="polite">{value}</span><button aria-label="Increase quantity" disabled={disabled || value >= 10} onClick={() => onChange(value + 1)}>+</button></div>; }
export function CartContents() { const { cart, busy, error, update, checkout, setOpen } = useStore(); if (!cart && !error) return <p role="status">Opening your bag…</p>; return <><div role="alert">{error && <p className="form-error">{error}</p>}</div>{!cart?.lines.length ? <div className="empty-cart"><Icon name="bag" size={64}/><h3>A little room for coconut.</h3><p>Your hair ritual starts with one bottle.</p><Link className="button" href="/shop" onClick={() => setOpen(false)}>Find your size</Link></div> : <><div className="cart-lines">{cart.lines.map(line => <div className="cart-line" key={line.id}><Bottle size={String(line.variant.ml)}/><div><h3>Ceema Coconut Hair Oil</h3><p>{line.variant.title} · {money(line.variant.price, line.variant.currency)}</p><Quantity value={line.quantity} disabled={busy} onChange={q => update(line.id, q)}/><button className="text-button remove" disabled={busy} onClick={() => update(line.id, 0)}>Remove</button></div></div>)}</div><div className="cart-summary"><div><span>Subtotal</span><strong>{money(cart.total, cart.lines[0]?.variant.currency)}</strong></div><p>Shipping and taxes confirmed at checkout.</p>{cart.demo && <p className="preview-note">Preview prices. No payment will be taken.</p>}<button className="button full" onClick={checkout} disabled={busy}>{busy ? 'Updating bag…' : 'Continue to checkout'}</button><Link href="/cart" className="text-button" onClick={() => setOpen(false)}>View your bag</Link></div></> }</>; }
export function BuyBox({ product, compact = false, initialSize }: { product: Product; compact?: boolean; initialSize?: string }) { const [selected, setSelected] = useState(product.variants.find(v => String(v.ml) === initialSize) || product.variants[0]); const [quantity, setQuantity] = useState(1); const [pin, setPin] = useState(''); const [delivery, setDelivery] = useState(''); const { add, busy } = useStore(); return <div className="buy-box">{!compact && <><p className="product-category">Your coconut hair ritual</p><h1>{product.title}</h1><p>{product.description}</p></>}<div className="price"><strong>{money(selected.price, selected.currency)}</strong><span>{money(selected.price / selected.ml, selected.currency)} / ml</span></div>{product.demo && <p className="preview-note">Preview price · final price to be confirmed</p>}<fieldset className="variant-picker"><legend>Choose your size</legend>{product.variants.map(v => <label className={v.id === selected.id ? 'variant selected' : 'variant'} key={v.id}><input type="radio" name={compact ? 'compact-size' : 'product-size'} checked={v.id === selected.id} onChange={() => setSelected(v)}/><span>{v.title}</span><small>{money(v.price, v.currency)}{!v.available ? ' · Sold out' : ''}</small></label>)}</fieldset><div className="purchase-row"><Quantity value={quantity} onChange={setQuantity}/><button className="button" disabled={busy || !selected.available} onClick={() => add(selected.id, quantity)}>{busy ? 'Adding…' : selected.available ? 'Add to cart' : 'Sold out'}</button></div><button className="button secondary full" disabled={busy || !selected.available} onClick={() => add(selected.id, quantity, true)}>Buy now</button>{!compact && <><form className="pincode" onSubmit={e => { e.preventDefault(); setDelivery(/^\d{6}$/.test(pin) ? 'Pincode format looks right. Delivery availability and timing will be confirmed at checkout.' : 'Enter a 6-digit Indian pincode.'); }}><label htmlFor="pincode">Check delivery to your pincode</label><div><input id="pincode" inputMode="numeric" autoComplete="postal-code" maxLength={6} value={pin} onChange={e => setPin(e.target.value.replace(/\D/g, ''))} placeholder="Enter pincode"/><button type="submit">Check</button></div><p role="status">{delivery}</p></form><div className="buy-trust"><Icon name="lock" size={18}/><span>Secure Shopify checkout when connected</span></div><div className="mobile-buy"><span>{selected.title}<strong>{money(selected.price, selected.currency)}</strong></span><button className="button" disabled={busy || !selected.available} onClick={() => add(selected.id, quantity)}>{busy ? 'Adding…' : 'Add to cart'}</button></div></>}</div>; }

