import sharp from 'sharp';
import fs from 'node:fs/promises';
import path from 'node:path';
const dir = path.resolve('public/images');
const label = (w,h,size='500 ml') => Buffer.from(`<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 300 370"><g fill="#0B5D6B" text-anchor="middle"><text x="150" y="114" font-family="Arial,sans-serif" font-size="66" font-weight="bold" letter-spacing="-5">ceema</text><path d="M150 155c-9 14-24 27-24 40a24 24 0 0 0 48 0c0-13-15-26-24-40Z" fill="none" stroke="#0B5D6B" stroke-width="2"/><path d="M140 194c0 7 4 12 11 12" fill="none" stroke="#0B5D6B" stroke-width="2"/><text x="150" y="257" font-family="Arial,sans-serif" font-size="21">Coconut</text><text x="150" y="286" font-family="Arial,sans-serif" font-size="21">hair oil</text><text x="150" y="330" font-family="Arial,sans-serif" font-size="14">${size}</text></g></svg>`);
const overlays = {'bottle-500.png': {left:271,top:547,width:483,height:639,size:'500 ml'}, 'bottle-1000.png':{left:206,top:530,width:611,height:670,size:'1 litre'}, 'gallery-label.png':{left:175,top:113,width:903,height:965,size:'500 ml'}, 'hero-splash.png': {left:912,top:390,width:296,height:375,size:'500 ml'},'lifestyle.png':{left:455,top:445,width:334,height:444,size:'500 ml'}};
for (const file of await fs.readdir(dir)) { if (!file.endsWith('.png') || file === 'og.png') continue; let image = sharp(path.join(dir,file)); const overlay=overlays[file]; if(overlay) image=image.composite([{input:label(overlay.width,overlay.height,overlay.size),left:overlay.left,top:overlay.top}]); let buffer=await image.png().toBuffer(); if(file.startsWith('hero-')) { const scene=await sharp(buffer).resize(1536,1024,{fit:'fill'}).png().toBuffer(); const extension=await sharp(scene).extract({left:0,top:0,width:1,height:1024}).resize(384,1024,{fit:'fill'}).png().toBuffer(); buffer=await sharp({create:{width:1920,height:1024,channels:4,background:'#8FE3E1'}}).composite([{input:extension,left:0,top:0},{input:scene,left:384,top:0}]).png().toBuffer(); } const target=path.join(dir,file.replace('.png','.webp')); const width=file.startsWith('hair-')||file.startsWith('review-video-')?700:file.startsWith('hero-')?1920:1100; await sharp(buffer).resize({width,withoutEnlargement:true}).webp({quality:85}).toFile(target); }
await fs.copyFile(path.join(dir,'hero-splash.webp'),path.join(dir,'hero-poster.webp'));
const small=await sharp(path.join(dir,'bottle-500.webp')).resize({height:710}).png().toBuffer();
const large=await sharp(path.join(dir,'bottle-1000.webp')).resize({height:870}).png().toBuffer();
await sharp({create:{width:1400,height:1050,channels:4,background:'#d9f0ef'}}).composite([{input:small,left:145,top:245},{input:large,left:690,top:85}]).webp({quality:88}).toFile(path.join(dir,'size-comparison.webp'));
const wordmark=(mono=false)=>`<svg xmlns="http://www.w3.org/2000/svg" width="260" height="88" viewBox="0 0 260 88"><g fill="${mono?'currentColor':'#0B5D6B'}"><text x="7" y="65" font-family="Arial,sans-serif" font-weight="bold" font-size="77" letter-spacing="-6">ceema</text><path d="M243 34c-3 5-9 11-9 16a9 9 0 0 0 18 0c0-5-6-11-9-16Z"/></g></svg>`;
await fs.writeFile(path.join(dir,'ceema-logo.svg'),wordmark()); await fs.writeFile(path.join(dir,'ceema-logo-mono.svg'),wordmark(true));
const ogCopy=Buffer.from('<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630"><g fill="#0B5D6B" font-family="Arial,sans-serif" font-weight="bold"><text x="65" y="90" font-size="55" letter-spacing="-4">ceema</text><text x="65" y="235" font-size="65" letter-spacing="-3">A little coconut.</text><text x="65" y="310" font-size="65" letter-spacing="-3">A lot of good</text><text x="65" y="385" font-size="65" letter-spacing="-3">hair days.</text><text x="65" y="510" font-size="23" font-weight="normal">Coconut hair oil · 500 ml &amp; 1 litre</text></g></svg>');
await sharp(path.join(dir,'hero-splash.webp')).resize(1200,630,{fit:'cover'}).composite([{input:ogCopy}]).png().toFile(path.join(dir,'og.png'));
console.log('Prepared optimized assets, labeled renders, SVG logos and OG image.');
